import { EDITOR_COMMAND_CATALOG } from '@/editor-v2/commands/catalog';
import { DEFAULT_UPLOAD_TO_CLOUD_SHORTCUT } from '@/types/settings';
import type { EditorCommandCategory } from '@/types/editor-v2';
import type { SettingsItem } from '../settings-registry';

const EDITOR_COMMAND_SECTIONS: Record<EditorCommandCategory, string> = {
  project: 'Editor V2 Project',
  edit: 'Editor V2 Edit',
  'tools-effects': 'Editor V2 Tools and Effects',
  playback: 'Editor V2 Playback',
  'timeline-tracks': 'Editor V2 Timeline and Tracks',
  'workspace-focus': 'Editor V2 Workspace and Focus',
};

const EDITOR_V2_SHORTCUT_ITEMS: SettingsItem[] = EDITOR_COMMAND_CATALOG.map(
  command => ({
    id: `shortcuts.editorV2.${command.id}`,
    category: 'shortcuts',
    section: EDITOR_COMMAND_SECTIONS[command.category],
    type: 'editor-command-shortcut',
    commandId: command.id,
    label: command.label,
    description: command.description,
    keywords: [
      'shortcut',
      'video',
      'editor',
      'v2',
      command.category,
      command.id,
    ],
  })
);

export const SHORTCUTS_ITEMS: SettingsItem[] = [
  {
    id: 'shortcuts.screenshot.area',
    category: 'shortcuts',
    section: 'Screenshot Shortcuts',
    type: 'shortcut',
    label: 'Capture Area',
    description: 'Keyboard shortcut for area capture',
    keywords: ['shortcut', 'hotkey', 'area', 'capture', 'screenshot'],
    getValue: s => s.shortcuts.screenshot.area,
    setValue: (s, v) => ({
      shortcuts: {
        ...s.shortcuts,
        screenshot: { ...s.shortcuts.screenshot, area: v },
      },
    }),
  },
  {
    id: 'shortcuts.screenshot.window',
    category: 'shortcuts',
    section: 'Screenshot Shortcuts',
    type: 'shortcut',
    label: 'Capture Window',
    description: 'Keyboard shortcut for window capture',
    keywords: ['shortcut', 'hotkey', 'window', 'capture', 'screenshot'],
    getValue: s => s.shortcuts.screenshot.window,
    setValue: (s, v) => ({
      shortcuts: {
        ...s.shortcuts,
        screenshot: { ...s.shortcuts.screenshot, window: v },
      },
    }),
  },
  {
    id: 'shortcuts.screenshot.screen',
    category: 'shortcuts',
    section: 'Screenshot Shortcuts',
    type: 'shortcut',
    label: 'Capture Full Screen',
    description: 'Keyboard shortcut for full screen capture',
    keywords: ['shortcut', 'hotkey', 'screen', 'full', 'capture'],
    getValue: s => s.shortcuts.screenshot.screen,
    setValue: (s, v) => ({
      shortcuts: {
        ...s.shortcuts,
        screenshot: { ...s.shortcuts.screenshot, screen: v },
      },
    }),
  },
  {
    id: 'shortcuts.timerCapture',
    category: 'shortcuts',
    section: 'Screenshot Shortcuts',
    type: 'shortcut',
    label: 'Timer Capture',
    description: 'Keyboard shortcut for timer capture',
    keywords: ['shortcut', 'hotkey', 'timer', 'delay', 'capture'],
    getValue: s => s.shortcuts.timerCapture ?? '',
    setValue: (s, v) => ({
      shortcuts: { ...s.shortcuts, timerCapture: v },
    }),
  },
  {
    id: 'shortcuts.recording.area',
    category: 'shortcuts',
    section: 'Recording Shortcuts',
    type: 'shortcut',
    label: 'Record Area',
    description: 'Keyboard shortcut for area recording',
    keywords: ['shortcut', 'hotkey', 'area', 'record', 'video'],
    getValue: s => s.shortcuts.recording.area,
    setValue: (s, v) => ({
      shortcuts: {
        ...s.shortcuts,
        recording: { ...s.shortcuts.recording, area: v },
      },
    }),
  },
  {
    id: 'shortcuts.recording.window',
    category: 'shortcuts',
    section: 'Recording Shortcuts',
    type: 'shortcut',
    label: 'Record Window',
    description: 'Keyboard shortcut for window recording',
    keywords: ['shortcut', 'hotkey', 'window', 'record', 'video'],
    getValue: s => s.shortcuts.recording.window,
    setValue: (s, v) => ({
      shortcuts: {
        ...s.shortcuts,
        recording: { ...s.shortcuts.recording, window: v },
      },
    }),
  },
  {
    id: 'shortcuts.recording.screen',
    category: 'shortcuts',
    section: 'Recording Shortcuts',
    type: 'shortcut',
    label: 'Record Screen',
    description: 'Keyboard shortcut for screen recording',
    keywords: ['shortcut', 'hotkey', 'screen', 'record', 'video'],
    getValue: s => s.shortcuts.recording.screen,
    setValue: (s, v) => ({
      shortcuts: {
        ...s.shortcuts,
        recording: { ...s.shortcuts.recording, screen: v },
      },
    }),
  },
  {
    id: 'shortcuts.captureText',
    category: 'shortcuts',
    section: 'Other Shortcuts',
    type: 'shortcut',
    label: 'Capture Text (OCR)',
    description: 'Keyboard shortcut for text capture',
    keywords: ['shortcut', 'hotkey', 'ocr', 'text', 'capture'],
    getValue: s => s.shortcuts.captureText,
    setValue: (s, v) => ({
      shortcuts: { ...s.shortcuts, captureText: v },
    }),
  },
  {
    id: 'shortcuts.scanQRCode',
    category: 'shortcuts',
    section: 'Other Shortcuts',
    type: 'shortcut',
    label: 'Scan QR Code',
    description: 'Keyboard shortcut for QR code scanning',
    keywords: ['shortcut', 'hotkey', 'qr', 'code', 'scan'],
    getValue: s => s.shortcuts.scanQRCode ?? '',
    setValue: (s, v) => ({
      shortcuts: { ...s.shortcuts, scanQRCode: v },
    }),
  },
  {
    id: 'shortcuts.history',
    category: 'shortcuts',
    section: 'Other Shortcuts',
    type: 'shortcut',
    label: 'Open History',
    description: 'Keyboard shortcut for opening history',
    keywords: ['shortcut', 'hotkey', 'history', 'recent'],
    getValue: s => s.shortcuts.history ?? '',
    setValue: (s, v) => ({
      shortcuts: { ...s.shortcuts, history: v },
    }),
  },
  {
    id: 'shortcuts.allInOne',
    category: 'shortcuts',
    section: 'Other Shortcuts',
    type: 'shortcut',
    label: 'All-in-one',
    description: 'Keyboard shortcut for all-in-one mode',
    keywords: ['shortcut', 'hotkey', 'all in one', 'all-in-one'],
    getValue: s => s.shortcuts.allInOne ?? '',
    setValue: (s, v) => ({
      shortcuts: { ...s.shortcuts, allInOne: v },
    }),
  },
  {
    id: 'shortcuts.openInEditor',
    category: 'shortcuts',
    section: 'Other Shortcuts',
    type: 'shortcut',
    label: 'Open in Editor',
    description: 'Keyboard shortcut for opening in editor',
    keywords: ['shortcut', 'hotkey', 'editor', 'open'],
    getValue: s => s.shortcuts.openInEditor ?? '',
    setValue: (s, v) => ({
      shortcuts: { ...s.shortcuts, openInEditor: v },
    }),
  },
  {
    id: 'shortcuts.clipboardInEditor',
    category: 'shortcuts',
    section: 'Other Shortcuts',
    type: 'shortcut',
    label: 'Open Clipboard in Editor',
    description: 'Keyboard shortcut for opening clipboard in editor',
    keywords: ['shortcut', 'hotkey', 'clipboard', 'editor', 'paste'],
    getValue: s => s.shortcuts.clipboardInEditor ?? '',
    setValue: (s, v) => ({
      shortcuts: { ...s.shortcuts, clipboardInEditor: v },
    }),
  },
  {
    id: 'shortcuts.editor.pen',
    category: 'shortcuts',
    section: 'Editor Tool Shortcuts',
    type: 'shortcut',
    singleKey: true,
    label: 'Pen Tool',
    description: 'Keyboard shortcut for pen tool',
    keywords: ['shortcut', 'editor', 'pen', 'draw', 'tool'],
    getValue: s => s.shortcuts.editor?.pen ?? 'p',
    setValue: (s, v) => ({
      shortcuts: {
        ...s.shortcuts,
        editor: { ...s.shortcuts.editor, pen: v },
      },
    }),
  },
  {
    id: 'shortcuts.editor.highlight',
    category: 'shortcuts',
    section: 'Editor Tool Shortcuts',
    type: 'shortcut',
    singleKey: true,
    label: 'Highlight Tool',
    description: 'Keyboard shortcut for highlight tool',
    keywords: ['shortcut', 'editor', 'highlight', 'marker', 'tool'],
    getValue: s => s.shortcuts.editor?.highlight ?? 'h',
    setValue: (s, v) => ({
      shortcuts: {
        ...s.shortcuts,
        editor: { ...s.shortcuts.editor, highlight: v },
      },
    }),
  },
  {
    id: 'shortcuts.editor.rectangle',
    category: 'shortcuts',
    section: 'Editor Tool Shortcuts',
    type: 'shortcut',
    singleKey: true,
    label: 'Rectangle Tool',
    description: 'Keyboard shortcut for rectangle tool',
    keywords: ['shortcut', 'editor', 'rectangle', 'box', 'shape', 'tool'],
    getValue: s => s.shortcuts.editor?.rectangle ?? 'r',
    setValue: (s, v) => ({
      shortcuts: {
        ...s.shortcuts,
        editor: { ...s.shortcuts.editor, rectangle: v },
      },
    }),
  },
  {
    id: 'shortcuts.editor.circle',
    category: 'shortcuts',
    section: 'Editor Tool Shortcuts',
    type: 'shortcut',
    singleKey: true,
    label: 'Circle Tool',
    description: 'Keyboard shortcut for circle tool',
    keywords: ['shortcut', 'editor', 'circle', 'oval', 'shape', 'tool'],
    getValue: s => s.shortcuts.editor?.circle ?? 'o',
    setValue: (s, v) => ({
      shortcuts: {
        ...s.shortcuts,
        editor: { ...s.shortcuts.editor, circle: v },
      },
    }),
  },
  {
    id: 'shortcuts.editor.line',
    category: 'shortcuts',
    section: 'Editor Tool Shortcuts',
    type: 'shortcut',
    singleKey: true,
    label: 'Line Tool',
    description: 'Keyboard shortcut for line tool',
    keywords: ['shortcut', 'editor', 'line', 'tool'],
    getValue: s => s.shortcuts.editor?.line ?? 'l',
    setValue: (s, v) => ({
      shortcuts: {
        ...s.shortcuts,
        editor: { ...s.shortcuts.editor, line: v },
      },
    }),
  },
  {
    id: 'shortcuts.editor.arrow',
    category: 'shortcuts',
    section: 'Editor Tool Shortcuts',
    type: 'shortcut',
    singleKey: true,
    label: 'Arrow Tool',
    description: 'Keyboard shortcut for arrow tool',
    keywords: ['shortcut', 'editor', 'arrow', 'pointer', 'tool'],
    getValue: s => s.shortcuts.editor?.arrow ?? 'a',
    setValue: (s, v) => ({
      shortcuts: {
        ...s.shortcuts,
        editor: { ...s.shortcuts.editor, arrow: v },
      },
    }),
  },
  {
    id: 'shortcuts.editor.text',
    category: 'shortcuts',
    section: 'Editor Tool Shortcuts',
    type: 'shortcut',
    singleKey: true,
    label: 'Text Tool',
    description: 'Keyboard shortcut for text tool',
    keywords: ['shortcut', 'editor', 'text', 'type', 'tool'],
    getValue: s => s.shortcuts.editor?.text ?? 't',
    setValue: (s, v) => ({
      shortcuts: {
        ...s.shortcuts,
        editor: { ...s.shortcuts.editor, text: v },
      },
    }),
  },
  {
    id: 'shortcuts.editor.number',
    category: 'shortcuts',
    section: 'Editor Tool Shortcuts',
    type: 'shortcut',
    singleKey: true,
    label: 'Number Tool',
    description: 'Keyboard shortcut for number tool',
    keywords: ['shortcut', 'editor', 'number', 'counter', 'tool'],
    getValue: s => s.shortcuts.editor?.number ?? 'n',
    setValue: (s, v) => ({
      shortcuts: {
        ...s.shortcuts,
        editor: { ...s.shortcuts.editor, number: v },
      },
    }),
  },
  {
    id: 'shortcuts.editor.redact',
    category: 'shortcuts',
    section: 'Editor Tool Shortcuts',
    type: 'shortcut',
    singleKey: true,
    label: 'Redact Tool',
    description: 'Keyboard shortcut for redact tool',
    keywords: ['shortcut', 'editor', 'redact', 'blur', 'pixelate', 'tool'],
    getValue: s => s.shortcuts.editor?.redact ?? 'x',
    setValue: (s, v) => ({
      shortcuts: {
        ...s.shortcuts,
        editor: { ...s.shortcuts.editor, redact: v },
      },
    }),
  },
  {
    id: 'shortcuts.editor.select',
    category: 'shortcuts',
    section: 'Editor Tool Shortcuts',
    type: 'shortcut',
    singleKey: true,
    label: 'Select Tool',
    description: 'Keyboard shortcut for select tool',
    keywords: ['shortcut', 'editor', 'select', 'move', 'tool'],
    getValue: s => s.shortcuts.editor?.select ?? 'v',
    setValue: (s, v) => ({
      shortcuts: {
        ...s.shortcuts,
        editor: { ...s.shortcuts.editor, select: v },
      },
    }),
  },
  {
    id: 'shortcuts.editor.crop',
    category: 'shortcuts',
    section: 'Editor Tool Shortcuts',
    type: 'shortcut',
    singleKey: true,
    label: 'Crop Tool',
    description: 'Keyboard shortcut for crop tool',
    keywords: ['shortcut', 'editor', 'crop', 'trim', 'tool'],
    getValue: s => s.shortcuts.editor?.crop ?? 'c',
    setValue: (s, v) => ({
      shortcuts: {
        ...s.shortcuts,
        editor: { ...s.shortcuts.editor, crop: v },
      },
    }),
  },
  {
    id: 'shortcuts.editor.wallpaper',
    category: 'shortcuts',
    section: 'Editor Tool Shortcuts',
    type: 'shortcut',
    singleKey: true,
    label: 'Wallpaper Tool',
    description: 'Keyboard shortcut for wallpaper tool',
    keywords: ['shortcut', 'editor', 'wallpaper', 'background', 'tool'],
    getValue: s => s.shortcuts.editor?.wallpaper ?? 'w',
    setValue: (s, v) => ({
      shortcuts: {
        ...s.shortcuts,
        editor: { ...s.shortcuts.editor, wallpaper: v },
      },
    }),
  },
  {
    id: 'shortcuts.editorActions.uploadToCloud',
    category: 'shortcuts',
    section: 'Editor Action Shortcuts',
    type: 'shortcut',
    label: 'Upload to Cloud',
    description: 'Keyboard shortcut for uploading the screenshot to cloud',
    keywords: ['shortcut', 'editor', 'cloud', 'upload', 'share'],
    getValue: s =>
      s.shortcuts.editorActions?.uploadToCloud ??
      DEFAULT_UPLOAD_TO_CLOUD_SHORTCUT,
    setValue: (s, v) => ({
      shortcuts: {
        ...s.shortcuts,
        editorActions: { ...s.shortcuts.editorActions, uploadToCloud: v },
      },
    }),
  },
  {
    id: 'shortcuts.videoEditorSidebar.cursor',
    category: 'shortcuts',
    section: 'Video Editor Shortcuts',
    type: 'shortcut',
    singleKey: true,
    label: 'Cursor Panel',
    description: 'Keyboard shortcut for cursor panel',
    keywords: ['shortcut', 'video', 'editor', 'cursor', 'panel'],
    getValue: s => s.shortcuts.videoEditorSidebar?.cursor ?? 'q',
    setValue: (s, v) => ({
      shortcuts: {
        ...s.shortcuts,
        videoEditorSidebar: { ...s.shortcuts.videoEditorSidebar, cursor: v },
      },
    }),
  },
  {
    id: 'shortcuts.videoEditorSidebar.zoom',
    category: 'shortcuts',
    section: 'Video Editor Shortcuts',
    type: 'shortcut',
    singleKey: true,
    label: 'Zoom Panel',
    description: 'Keyboard shortcut for zoom panel',
    keywords: ['shortcut', 'video', 'editor', 'zoom', 'panel'],
    getValue: s => s.shortcuts.videoEditorSidebar?.zoom ?? 'z',
    setValue: (s, v) => ({
      shortcuts: {
        ...s.shortcuts,
        videoEditorSidebar: { ...s.shortcuts.videoEditorSidebar, zoom: v },
      },
    }),
  },
  {
    id: 'shortcuts.videoEditorSidebar.drawing',
    category: 'shortcuts',
    section: 'Video Editor Shortcuts',
    type: 'shortcut',
    singleKey: true,
    label: 'Drawing Panel',
    description: 'Keyboard shortcut for drawing panel',
    keywords: ['shortcut', 'video', 'editor', 'drawing', 'panel'],
    getValue: s => s.shortcuts.videoEditorSidebar?.drawing ?? 'd',
    setValue: (s, v) => ({
      shortcuts: {
        ...s.shortcuts,
        videoEditorSidebar: { ...s.shortcuts.videoEditorSidebar, drawing: v },
      },
    }),
  },
  {
    id: 'shortcuts.videoEditorSidebar.camera',
    category: 'shortcuts',
    section: 'Video Editor Shortcuts',
    type: 'shortcut',
    singleKey: true,
    label: 'Camera Panel',
    description: 'Keyboard shortcut for camera panel',
    keywords: ['shortcut', 'video', 'editor', 'camera', 'panel'],
    getValue: s => s.shortcuts.videoEditorSidebar?.camera ?? 'm',
    setValue: (s, v) => ({
      shortcuts: {
        ...s.shortcuts,
        videoEditorSidebar: { ...s.shortcuts.videoEditorSidebar, camera: v },
      },
    }),
  },
  {
    id: 'shortcuts.videoEditorSidebar.audio',
    category: 'shortcuts',
    section: 'Video Editor Shortcuts',
    type: 'shortcut',
    singleKey: true,
    label: 'Audio Panel',
    description: 'Keyboard shortcut for audio panel',
    keywords: ['shortcut', 'video', 'editor', 'audio', 'sound', 'panel'],
    getValue: s => s.shortcuts.videoEditorSidebar?.audio ?? 'a',
    setValue: (s, v) => ({
      shortcuts: {
        ...s.shortcuts,
        videoEditorSidebar: { ...s.shortcuts.videoEditorSidebar, audio: v },
      },
    }),
  },
  {
    id: 'shortcuts.videoEditorSidebar.wallpaper',
    category: 'shortcuts',
    section: 'Video Editor Shortcuts',
    type: 'shortcut',
    singleKey: true,
    label: 'Wallpaper Panel',
    description: 'Keyboard shortcut for wallpaper panel',
    keywords: ['shortcut', 'video', 'editor', 'wallpaper', 'background'],
    getValue: s => s.shortcuts.videoEditorSidebar?.wallpaper ?? 'w',
    setValue: (s, v) => ({
      shortcuts: {
        ...s.shortcuts,
        videoEditorSidebar: {
          ...s.shortcuts.videoEditorSidebar,
          wallpaper: v,
        },
      },
    }),
  },
  {
    id: 'shortcuts.videoEditorSidebar.keyboard',
    category: 'shortcuts',
    section: 'Video Editor Shortcuts',
    type: 'shortcut',
    singleKey: true,
    label: 'Keyboard Panel',
    description: 'Keyboard shortcut for keyboard panel',
    keywords: ['shortcut', 'video', 'editor', 'keyboard', 'panel'],
    getValue: s => s.shortcuts.videoEditorSidebar?.keyboard ?? 'k',
    setValue: (s, v) => ({
      shortcuts: {
        ...s.shortcuts,
        videoEditorSidebar: { ...s.shortcuts.videoEditorSidebar, keyboard: v },
      },
    }),
  },
  {
    id: 'shortcuts.videoEditorSidebar.subtitle',
    category: 'shortcuts',
    section: 'Video Editor Shortcuts',
    type: 'shortcut',
    singleKey: true,
    label: 'Subtitle Panel',
    description: 'Keyboard shortcut for subtitle panel',
    keywords: ['shortcut', 'video', 'editor', 'subtitle', 'caption', 'panel'],
    getValue: s => s.shortcuts.videoEditorSidebar?.subtitle ?? 's',
    setValue: (s, v) => ({
      shortcuts: {
        ...s.shortcuts,
        videoEditorSidebar: { ...s.shortcuts.videoEditorSidebar, subtitle: v },
      },
    }),
  },
  {
    id: 'shortcuts.videoEditorSidebar.first-frame',
    category: 'shortcuts',
    section: 'Video Editor Shortcuts',
    type: 'shortcut',
    singleKey: true,
    label: 'First Frame Panel',
    description: 'Keyboard shortcut for first frame panel',
    keywords: ['shortcut', 'video', 'editor', 'first frame', 'thumbnail'],
    getValue: s => s.shortcuts.videoEditorSidebar?.['first-frame'] ?? 'f',
    setValue: (s, v) => ({
      shortcuts: {
        ...s.shortcuts,
        videoEditorSidebar: {
          ...s.shortcuts.videoEditorSidebar,
          'first-frame': v,
        },
      },
    }),
  },
  {
    id: 'shortcuts.videoEditorSidebar.export',
    category: 'shortcuts',
    section: 'Video Editor Shortcuts',
    type: 'shortcut',
    singleKey: true,
    label: 'Export Panel',
    description: 'Keyboard shortcut for export panel',
    keywords: ['shortcut', 'video', 'editor', 'export', 'render', 'panel'],
    getValue: s => s.shortcuts.videoEditorSidebar?.export ?? 'e',
    setValue: (s, v) => ({
      shortcuts: {
        ...s.shortcuts,
        videoEditorSidebar: { ...s.shortcuts.videoEditorSidebar, export: v },
      },
    }),
  },
  ...EDITOR_V2_SHORTCUT_ITEMS,
];
